#!/bin/bash
#PBS -N sequential_sbc_with_rewrites
#PBS -l select=1:ncpus=1:mem=32gb
#PBS -l walltime=72:00:00
#PBS -j oe
#PBS -M kai.samaroo22@imperial.ac.uk
#PBS -m bea
#PBS -o sequential_sbc_with_rewrites_most_recent.log


sigma=${sigma:-1}
N_iter=${N_iter:-1000}
N_samp=${N_samp:-1000}
num_sequential_rounds=${num_sequential_rounds:-4}
num_simulations_per_round=${num_simulations_per_round:-5000}
experiment_ID=${experiment_ID:--1}
n=${n:-1}
d=${d:-1}
L=${L:--1}
U=${U:-1}

cd $PBS_O_WORKDIR

module load Python/3.9.6-GCCcore-11.2.0

source ~/venvs/sbi_venv/bin/activate

python sequential_sbc_with_rewrites.py --sigma ${sigma} --N_iter ${N_iter} --N_samp ${N_samp} --num_sequential_rounds ${num_sequential_rounds} --num_simulations_per_round ${num_simulations_per_round} --experiment_ID ${experiment_ID} --d ${d} --n ${n} --L ${L} --U ${U}
