#!/bin/bash
#PBS -N tsnpe_d100_sequential_posterior_KLs_and_squared_norms
#PBS -l select=1:ncpus=1:mem=32gb
#PBS -l walltime=72:00:00
#PBS -j oe
#PBS -M kai.samaroo22@imperial.ac.uk
#PBS -m bea
#PBS -o tsnpe_d100_sequential_posterior_KLs_and_squared_norms_most_recent.log

cd $PBS_O_WORKDIR

module load Python/3.9.6-GCCcore-11.2.0

source ~/venvs/sbi_venv/bin/activate

python tsnpe/sequential_posterior_KLs_and_squared_norms.py --d 100 --L -11.66 --U 11.66 --x_observed 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 --num_repetitions 10 --num_sequential_rounds 8 --restricted_prior_sample_with "sir"