#!/bin/bash
#PBS -N tsnpe_d50_sequential_posterior_KLs_and_squared_norms
#PBS -l select=1:ncpus=1:mem=32gb
#PBS -l walltime=72:00:00
#PBS -j oe
#PBS -M kai.samaroo22@imperial.ac.uk
#PBS -m bea
#PBS -o tsnpe_d50_sequential_posterior_KLs_and_squared_norms_most_recent.log

cd $PBS_O_WORKDIR

module purge
module load tools/prod
module load Python/3.9.6-GCCcore-11.2.0

source ~/venvs/sbi_venv/bin/activate

python tsnpe/sequential_posterior_KLs_and_squared_norms.py --d 50 --L -8.73 --U 8.73 --x_observed 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 --num_repetitions 10 --num_sequential_rounds 8 --restricted_prior_sample_with "sir" --save_posteriors "True"
