#!/bin/bash
#PBS -N sequential_posterior_leakage_factors_d_list
#PBS -l select=1:ncpus=1:mem=32gb
#PBS -l walltime=72:00:00
#PBS -j oe
#PBS -M kai.samaroo22@imperial.ac.uk
#PBS -m bea
#PBS -o sequential_posterior_leakage_factors_d_list_most_recent.log

cd $PBS_O_WORKDIR

module load Python/3.9.6-GCCcore-11.2.0

source ~/venvs/sbi_venv/bin/activate

python sequential_posterior_leakage_factors.py --d_list 1 4 8 12 16 20
