#!/bin/bash
#PBS -N d50_sequential_posterior_KLs_and_squared_norms_only_tsnpe
#PBS -l select=1:ncpus=1:mem=32gb
#PBS -l walltime=72:00:00
#PBS -j oe
#PBS -M kai.samaroo22@imperial.ac.uk
#PBS -m bea
#PBS -o d50_sequential_posterior_KLs_and_squared_norms_only_tsnpe_most_recent.log

cd $PBS_O_WORKDIR

module load Python/3.9.6-GCCcore-11.2.0

source ~/venvs/sbi_venv/bin/activate

python tsnpe/sequential_posterior_KLs_and_squared_norms.py --d 50 --L -8.73 --U 8.73 --x_observed 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 --num_repetitions 10 --num_sequential_rounds 8 --restricted_prior_sample_with "sir"
